# Generated by Django 2.2.13 on 2020-08-21 13:41

from django.db import migrations

from oscar.apps.offer.custom import create_condition


def create_birthday_condition(apps, schema_editor):
    from oscar.apps.offer.conditions import BirthdayCondition

    create_condition(BirthdayCondition)


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_range_excluded_categories'),
    ]

    operations = [
        migrations.RunPython(create_birthday_condition)
    ]